export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const PEOPLE_RECEIVED = 'PEOPLE_RECEIVED';
export const PEOPLE_REQUEST_FAILED = 'PEOPLE_REQUEST_FAILED';
export const STARSHIP_REQUEST = 'STARSHIP_REQUEST';
export const STARSHIP_REQUEST_FAILED = 'STARSHIP_REQUEST_FAILED';
export const PLANET_REQUEST = 'PLANET_REQUEST';
export const PLANET_REQUEST_FAILED = 'PLANET_REQUEST_FAILED';

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
